name: CI with Docker & Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Build & start services in background
        run: |
          docker compose build --no-cache
          docker compose up -d
          sleep 10

      - name: Run test suite
        run: |
          docker compose run --rm web python -m pytest

      - name: Tear down
        if: always()
        run: docker compose down --volumes --remove-orphans